### ISSUE TITLE
Missing project file.

### ISSUE THREAD

**Issue by dmamalis** [TimB-QNA/openDynamics#3]
openDynamics.pro referred in [wiki](https://github.com/TimB-QNA/openDynamics/wiki/BuildInstructions) is missing from repo

**Comment by TimB-QNA** [comment]
You're quite right, I'll fix it. For the moment, you can build pdstrip using the project file in the pdstrip directory (just "cd pdstrip" then qmake etc).

**Comment by TimB-QNA** [comment]
Fixed.
