### ISSUE TITLE
Difference of geoConv and RAOplot

### ISSUE THREAD

**Issue by dmamalis** [TimB-QNA/openDynamics#4]
Could you please elaborate on the building of geoCOnv and RAOplot? From the source files these two seem to be functionally identical. 

``` 32c32
<   if (iType.toLower()=="section"){

---
>   if (iType=="section"){
37c37
<   if (iType.toLower()=="ghs"){

---
>   if (iType=="ghs"){
45c45
<   if (oType.toLower()=="point"){

---
>   if (oType=="point"){
54c54
<   if (oType.toLower()=="section"){

---
>   if (oType=="section"){
```

**Comment by TimB-QNA** [comment]
RAOplot appears to be legacy code. It has been superseded by the direct RAO output from pdStrip. I have removed RAOplot.
